# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "xV1/TDVZBV8LRoCnr5gCjK0F1dqZOA0HCq28tOzO6gzKofQV9+TFp4GWQRSxc0/ssUJwZ8gy9aBtBZSAKus7rllz3luwjwkQIjRd7zgzaQNkjsW6QREBbnXgI6bq0fvFR6/uJnVX0lN82RBKqxQ095XpoATlC0lIag7Crbw1vVtQpeu6kYonUNqswyfQndQo4vry29Xr9V9gqTiVpv06RdBzagdd/9J5JV2td7afRFLph9v1uvG6246R3vbbjZQFDHAheN+8eE5J3EUesb4BhOoOSiRdvQjTmfGJyemhb7Ox09VkRhbQT6KYMJx9p1bDFavO2PDKffMeLjP4z1wRpnQEVUr3q+w1TCqs9VPVgyIvfDj29Ol4hPM3Aw4/pUk+xVa5jnHyHnrG6TtWCZafZofXR65Cg/bpB5uddEa232kFEZvRtweMVLLI+yLrCuIDc4FB6aAhmR4MXer3cwIi0zR3Pqsiuf6K+sJ37DerSgZx5Ft7D4F7WDp3sPVwLyhJgUeZZMT73nKo7OdaeQeO/gX3XCUzKiI7hnZNibj5xJMn4qynS+8MZoIkbmdhkKCs49nfCfgHvYkJCIXrYXaSRHg6JU0UaxBVoKaiGuDfOjO7tVGNarj6ppwd+YXwu5zUG3LR3EsWoNBew99Q1jk8+4mN+acR7BJ2gJToTV5RASs="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
