travis:
  secure:
    BINSTAR_TOKEN: xV1/TDVZBV8LRoCnr5gCjK0F1dqZOA0HCq28tOzO6gzKofQV9+TFp4GWQRSxc0/ssUJwZ8gy9aBtBZSAKus7rllz3luwjwkQIjRd7zgzaQNkjsW6QREBbnXgI6bq0fvFR6/uJnVX0lN82RBKqxQ095XpoATlC0lIag7Crbw1vVtQpeu6kYonUNqswyfQndQo4vry29Xr9V9gqTiVpv06RdBzagdd/9J5JV2td7afRFLph9v1uvG6246R3vbbjZQFDHAheN+8eE5J3EUesb4BhOoOSiRdvQjTmfGJyemhb7Ox09VkRhbQT6KYMJx9p1bDFavO2PDKffMeLjP4z1wRpnQEVUr3q+w1TCqs9VPVgyIvfDj29Ol4hPM3Aw4/pUk+xVa5jnHyHnrG6TtWCZafZofXR65Cg/bpB5uddEa232kFEZvRtweMVLLI+yLrCuIDc4FB6aAhmR4MXer3cwIi0zR3Pqsiuf6K+sJ37DerSgZx5Ft7D4F7WDp3sPVwLyhJgUeZZMT73nKo7OdaeQeO/gX3XCUzKiI7hnZNibj5xJMn4qynS+8MZoIkbmdhkKCs49nfCfgHvYkJCIXrYXaSRHg6JU0UaxBVoKaiGuDfOjO7tVGNarj6ppwd+YXwu5zUG3LR3EsWoNBew99Q1jk8+4mN+acR7BJ2gJToTV5RASs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
