travis:
  secure:
    BINSTAR_TOKEN: W2syQXYCk/c4f0hCbbiDM0KtdrRZH4GEl5tyFYlv1WtsHu+slrhJHEYgYJn0tDJIVVcEh/oQqpBeueAn8q1hS1PUGpMYVgHwuDOLNLeRtOg+vE33pWxq8PnALfVJM7Eoeb1pJDqOttAfdbv55YVFVemwD6ttzHkAdA2Vwvqdu+OI0qnr0+jfAZfjuyDJzQO+W7etvg8Y9lTIj0N5gCCboabsYAmPl1OvpYoIcY/sukKza3LbKrdZ8WOW6jqBorCu5MChECYHlCpGPZjdJ231ZC8PhzWHA/N6KsDitmhe2E8BmSCKn7BX0esxfkr6uZqlpM2+xw2kGZeLVhSBR/uxcOlxlHXpKN9k4HwDp43CgQZ42RNziydJ7SZfrys4e2LPwbaf6PxpCpHM/2BSZJThIbZfhlCI0X38MBthsywWm44BT93fK7hvXmM9N7PIGAWf3tCl19wqBwvZzdy8Zrasd9Ccp63DWeDcouhEahAwIcsusEvKwvTNfnxolmJySZH7Xp6Mveg7bepnBobJ0s2udqbvl8njitv/d6xrEEPeD3q3jAfbh93KjrA5Ia6nzp/pQSGXAftaoROLLpMWvJk6EQWqxGSx3L42Vfq6ETw7YWCjwM9VgfMHgn5BBILvVB8EINjz150e09+AFwLRHCZjlaUQh7aXHrYc6kFlfrXRlMo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
