travis:
  secure:
    BINSTAR_TOKEN: sVQb4t2WF5JBjgU50NL/ylzjtODb1NuT/B1QP7qQq6B+2irFH2PtdRuInQaCkcUlEXOBxC3zYAwoSBs9sK+Uf4+XetOOfZEkLA7Kh76u/xubqfJ2n1ud2V0zl7hFbvJy+Xo2OsSDF2ZxoUDrYVnX8LohY4bZnU3ROeMdnEE5EzG1Jp64orVh2Oy2RJWWdyOXBvHiJ4pD6LBIsKdUsQ+EW8kN/CENe9llviT1Lz9v10Z3NIHkSZ2WVcvFMzPZ1fH/KtpSfQqPVJuIlsmBmIM0zmS91l+6pJ9myBnv9BIcSE70tCEbzbmgGNik22nJD2LitaHG0ChgF5xbZmtSjmIdyxdE4GliEb19Fa1TUYqZAAB6maB0+cXJQ1Pgq0S5ZetF9aWJW4W4lyzrwCDE/ChL39AVBD7oAxomIq2LSaFRHgXkU9iBHCm41l+iIe0LudAu/iIl3/Fwx0Z6trZZB2/0/zBXz/hroXjmhHfRPdYp+rr2qg5/16W07u6jM/t3zAAbpaUn8VP5/OG0zepTlMimtY+LX9ebId8xAHTgZlwvpR90Elk4w7ul6rZkM35KZdOm6uAJnxQVKgQ654/BbyhUfzFpPXb61OaOVtwLxil2lMGEyhvN+QTxrUccUJpBnkkk9cMfvIcP+sqyYi0uYdYKG2kp9xloLIq1M4r4PG+U5+U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
